---
# Disable checks that are not relevant for this tool
ignored:
  - DL3008  # Pin versions in apt-get
  - DL3025  # Use JSON notation for CMD
  - DL6001  # Use USER to switch to non-root user
  - DL6002  # HEALTHCHECK instruction
